# Machine learning

In [1]:
!pip install numpy

In [2]:
import numpy
print(dir(numpy))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split'

In [6]:
import numpy as np
a=np.array([1,2,3,4]) # we are writing under the array function
a

array([1, 2, 3, 4])

In [7]:
b=np.array([1,2])
b

array([1, 2])

In [8]:
c = np.array([[1,2,3,4],[5,6,7,8]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# now get the dimensions
a.ndim
# a has one dimension

1

In [10]:
b.ndim

1

In [11]:
c.ndim

2

In [12]:
# shape is for to view the rows and cloumns
a.shape


(4,)

In [13]:
b.shape

(2,)

In [14]:
c.shape

(2, 4)

In [15]:
a.dtype

dtype('int64')

In [16]:
b.dtype

dtype('int64')

In [17]:
c.dtype

dtype('int64')

In [27]:
print(f"a elements={a}\n,a datatype is {a.dtype}\n,a item size is {a.itemsize}")

a elements=[1 2 3 4]
,a datatype is int64
,a item size is 8


In [28]:
print(f"b elements = {b}\n, b datatype is {b.dtype}\n, b item size is {b.itemsize}")

b elements = [1 2]
, b datatype is int64
, b item size is 8


In [26]:
print(f"c elements = {c}\n c datatype is {c.dtype}\nc itemsize is {c.itemsize}")

c elements = [[1 2 3 4]
 [5 6 7 8]]
 c datatype is int64
c itemsize is 8


In [ ]:
# https://www.youtube.com/watch?v=UehuI1w10lg&t=265s (1:13)